### wandb
report_to: wandb
run_name: ChiseLLM-7B

### model
model_name_or_path: models/Qwen/Qwen2.5-Coder-7B-Instruct

### method
stage: sft
do_train: true
finetuning_type: full

### dataset
dataset_dir: datasets
dataset: ChiseLLM-Completion,ChiseLLM-Decompile
mix_strategy: interleave_under
interleave_probs: 0.3,0.7
template: qwen
cutoff_len: 16384
max_samples: 6000
overwrite_cache: true
preprocessing_num_workers: 48
dataloader_persistent_workers: true
dataloader_pin_memory: true
dataloader_num_workers: 48

### output
output_dir: output/ChiseLLM/ChiseLLM-7B
logging_steps: 1
save_steps: 1000
plot_loss: true

### train
per_device_train_batch_size: 2
gradient_accumulation_steps: 8
learning_rate: 1.0e-5
num_train_epochs: 3.0
lr_scheduler_type: cosine
warmup_ratio: 0.05
weight_decay: 0.0001
bf16: true
ddp_timeout: 180000000

# speedup
flash_attn: fa2
enable_liger_kernel: true

# memory
deepspeed: config/ds/ds_z3_config.json